DROP TABLE IF EXISTS sample_face_vectors;

CREATE TABLE sample_face_vectors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    vector TEXT NOT NULL
);